src/main/java/com/fpuna/sigeres/bean/SubGrupo.java
package com.fpuna.sigeres.bean;

import com.fpuna.sigeres.dao.DaoFactory;
import com.fpuna.sigeres.modelo.Grupos;
import com.fpuna.sigeres.modelo.SubGrupos;
import com.fpuna.util.Messages;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "subgrupobean")
@ViewScoped
public class SubGrupo implements Serializable {

    private SubGrupos subgrupo;
    private List<SubGrupos> lista;

    //metodos
    public void guardar() {
        try {
            if (subgrupo.getId() == null) {
                DaoFactory.getSubGrupoDAO().add(subgrupo);
            } else {
                DaoFactory.getSubGrupoDAO().edit(subgrupo);
            }
            Messages.infoMessage("Exito");
            resetFields();

        } catch (Exception e) {
            Messages.errorMessage("error");
        }
    }
    public void inactivar() {
        try {
            DaoFactory.getSubGrupoDAO().delete(subgrupo);
        } catch (Exception e) {

        }
    }
    private void resetFields() {
        this.subgrupo = new SubGrupos();
    }

    private boolean isPostBack() {
        return FacesContext.getCurrentInstance().isPostback();
    }

    public void listarCombo(boolean isback) throws Exception {
        try {
            if (isback == false) {
                if (isPostBack() == false) {
                    lista = DaoFactory.getSubGrupoDAO().getAll("ACTIVO");
                }
            } else {
                lista = DaoFactory.getSubGrupoDAO().getAll("ACTIVO");
            }
        } catch (Exception e) {
            throw e;
        } finally {

        }
    }
    
    public void listarTabla(boolean isback) throws Exception {
        try {
            if (isback == false) {
                if (isPostBack() == false) {
                    lista = DaoFactory.getSubGrupoDAO().getAll();
                }
            } else {
                lista = DaoFactory.getSubGrupoDAO().getAll();
            }
        } catch (Exception e) {
            throw e;
        } finally {

        }
    }

    public void listarComboById(Grupos id) {
        try {
            if (id != null) {
                lista = DaoFactory.getSubGrupoDAO().getAll(id);
            } else {
                //lista = DaoFactory.getDepositoDAO().getAll("ACTIVO");
                lista = null;
            }
        } catch (Exception e) {

        }
    }

    //constructor
    public SubGrupo() {
        this.subgrupo = new SubGrupos();
    }

    //Setter,getters
    public SubGrupos getSubGrupo() {
        return subgrupo;
    }

    public void setSubGrupo(SubGrupos subgrupo) {
        this.subgrupo = subgrupo;
    }

    public List<SubGrupos> getLista() {
        return lista;
    }

    public void setLista(List<SubGrupos> lista) {
        this.lista = lista;
    }

}

src/main/webapp/subgrupo/subgrupoform.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Subgrupos</title>
    </h:head>

    <body>
        <ui:composition template="./../templates/principal.xhtml">
            <ui:define name="content">  
                <f:event type="preRenderView" listener="#{grupobean.listarCombo(false)}" />
                <p:growl autoUpdate="true"/>

                <h:form>
                    <p:panelGrid columns="2" class="center-panelgrid">
                        <p:graphicImage name="imagenes/group.png"/>
                        <p:panelGrid
                            class="sp-tabla sin-borde size-components">
                            <f:facet name="header">
                                <p:row>
                                    <p:column colspan="6">
                                        <p:outputLabel value="Registrar Sub Grupo"/>
                                    </p:column>
                                </p:row>

                            </f:facet>
                            <p:row>
                                <p:column>
                                    <p:outputLabel value="Descripcion" for="id-txt-descripcion"/>
                                </p:column>
                                <p:column>
                                    <p:inputText id="id-txt-descripcion" required="true" value="#{subgrupobean.subGrupo.descripcion}"/>
                                </p:column>
                                <p:column>
                                    <p:message display="icon" for="id-txt-descripcion"/>
                                </p:column>
                                <p:column/>
                                <p:column/>
                                <p:column/>
                            </p:row>

                            <p:row>
                                <p:column colspan="6">
                                    <h:panelGrid columns="3">
                                        <p:outputLabel value="Estado" for="id-option-state"/>
                                        <p:selectOneMenu id="id-option-state" value="#{subgrupobean.subGrupo.estado}" >
                                            <f:selectItem itemLabel="Activo" itemValue="ACTIVO"/>
                                            <f:selectItem itemLabel="Inactivo" itemValue="INACTIVO"/>
                                        </p:selectOneMenu>
                                        <p:message display="icon" for="id-option-state"/>
                                    </h:panelGrid>

                                </p:column>
                            </p:row>

                            <f:facet name="footer">

                                <p:row>
                                    <p:column colspan="6">
                                        <p:commandButton value="Guardar"
                                                         icon="ui-icono-registrar"
                                                         class="save-button"
                                                         update="@form"
                                                         actionListener="#{subgrupobean.guardar()}"/>
                                    </p:column>
                                </p:row>

                            </f:facet>


                        </p:panelGrid>
                    </p:panelGrid>
                </h:form>


            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/subgrupo/subgrupotable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Usuario</title>
    </h:head>

    <body>
        <ui:composition template="./../templates/principal.xhtml">
            <p:growl autoUpdate="true"/>
            <ui:define name="content">
                <f:event type="preRenderView" listener="#{subgrupobean.listarCombo(false)}"/>
                <h:form id="formSubgrupo">
                    <p:fieldset class="generic-fielset">

                        <p:dataTable value="#{subgrupobean.lista}" var="subgrupo"
                                     id="datatable-subgrupo"
                                     style="width: auto"
                                     emptyMessage="Sin Registros"
                                     class="generic-table"
                                     rowIndexVar="linea"
                                     rows="5"
                                     paginator="true"
                                     rowsPerPageTemplate="5,10,15"
                                     paginatorPosition="bottom"
                                     widgetVar="subgrupoTable">


                            <f:facet name="header" class="header-search">
                                <h:panelGrid columns="2">
                                    <p:inputText id="globalFilter" 
                                                 onkeyup="PF('subgrupoTable').filter()" 
                                                 style="float: right"
                                                 placeholder="Busqueda Rapida"/>
                                </h:panelGrid>


                            </f:facet>

                            <p:column width="120" headerText="Acciones" style="text-align: center" class="class-acciones">
                                <p:commandLink update=":form-dialog" oncomplete="PF('depositoDialog').show()"
                                               title="View" class="acciones-hover">
                                    <f:setPropertyActionListener value="#{subgrupo}" target="#{subgrupobean.subGrupo}" />
                                    <p:graphicImage library="imagenes" name="view-glass.png" width="24" height="24"/>
                                </p:commandLink>
                                <p:link outcome="/deposito/depositoform">
                                    <f:param name="deposito" value="#{subgrupo.id}"/>
                                    <p:graphicImage library="imagenes" name="edit.png" width="24" height="24"/>
                                </p:link>

                                <p:commandLink update=":form-confirm-dialog:confirmDialog"
                                               oncomplete="PF('confirmDelete').show();">
                                    <p:graphicImage library="imagenes" name="cancel-2.png" width="24" height="24"/>
                                    <f:setPropertyActionListener value="#{subgrupo}" target="#{subgrupobean.subGrupo}" />

                                </p:commandLink>



                            </p:column>

                            <p:column headerText="Codigo"
                                      style="width: 120px; padding: 1px; text-align: center"
                                      filterBy="#{subgrupo.id}"
                                      filterMatchMode="exact">
                                #{subgrupo.id}
                            </p:column>
                            <p:column headerText="Descripción" 
                                      style="width: 450px; padding: 1px; text-align: center"
                                      filterStyleClass="filter-by-descripcion"
                                      filterBy="#{subgrupo.descripcion}"
                                      filterMatchMode="contains">
                                #{subgrupo.descripcion}
                            </p:column>
                            <p:column headerText="Estado"
                                      style="text-align: center; width: 150px"
                                      filterBy="#{subgrupo.estado}"
                                      filterMatchMode="exact"
                                      >
                                <f:facet name="filter">
                                    <p:selectOneMenu onchange="PF('subgrupoTable').filter()">
                                        <f:selectItem itemLabel="Seleccione" itemValue="#{null}" noSelectionOption="true" />
                                        <f:selectItem itemLabel="Activo" itemValue="ACTIVO" />
                                        <f:selectItem itemLabel="Inactivo" itemValue="INACTIVO" />
                                    </p:selectOneMenu>
                                </f:facet>
                                #{subgrupo.estado}
                            </p:column>

                        </p:dataTable>
                    </p:fieldset>
                </h:form>
                <h:form id="form-dialog">
                    <p:dialog header="Deposito Info" widgetVar="depositoDialog" 
                              modal="true" showEffect="fade" 
                              hideEffect="fade" resizable="false">
                        <p:outputPanel id="depositoDetail" style="text-align:center;">
                            <p:panelGrid  columns="2" rendered="#{not empty subgrupobean.lista}" 
                                          columnClasses="label-dialogo-view" class="panel-contenedor borde-bottom">

                                <h:outputText value="Codigo:" />
                                <h:outputText value="#{subgrupobean.subGrupo.id}" />

                                <h:outputText value="Descripción" />
                                <h:outputText value="#{subgrupobean.subGrupo.descripcion}" />

                                <h:outputText value="Estado:" />
                                <h:outputText value="#{subgrupobean.subGrupo.estado}"/>

                                <h:panelGroup/>
                                <p:commandLink oncomplete="PF('depositoDialog').hide()">
                                    <p:graphicImage name="imagenes\ok_image.png" style="float: right;height: 20px"
                                                    />
                                </p:commandLink>

                            </p:panelGrid>
                        </p:outputPanel>
                    </p:dialog>
                </h:form>
                <h:form id="form-confirm-dialog">
                    <p:confirmDialog id="confirmDialog"
                                     widgetVar="confirmDelete"
                                     header="Message"
                                     severity="alert"
                                     closeOnEscape="true"
                                     closable="true">

                        <p:commandButton id="btnYes"
                                         value="Si"
                                         process="@this"
                                         style="float: right"
                                         actionListener="#{subgrupobean.inactivar()}"
                                         oncomplete="PF('confirmDelete').hide()"
                                         update=":formSubgrupo:datatable-subgrupo"/>

                        <p:commandButton id="btnNo"
                                         style="float: right"
                                         value="No"
                                         onclick="PF('confirmDelete').hide()"
                                         type="button" />

                        <f:facet name="message">
                            <p:outputPanel>
                                <h:outputFormat value="Se eliminara a #{subgrupobean.subGrupo.descripcion}, confirmar?" escape="false"/>
                            </p:outputPanel>
                        </f:facet>
                    </p:confirmDialog>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>