src/main/java/com/fpuna/sigeres/bean/CiudadBean.java
package com.fpuna.sigeres.bean;

import com.fpuna.sigeres.dao.DaoFactory;
import com.fpuna.sigeres.modelo.Ciudades;
import com.fpuna.sigeres.modelo.Departamentos;
import com.fpuna.util.Messages;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "ciudadbean")
@ViewScoped
public class CiudadBean implements Serializable {

    private Ciudades ciudad;
    private List<Ciudades> lista;
    private List<Ciudades> listafiltro;

    //metodos
    public void guardar() {
        try {
            if (ciudad.getId() == null) {
                DaoFactory.getCiudadDAO().add(ciudad);
            } else {
                DaoFactory.getCiudadDAO().edit(ciudad);
            }
            Messages.infoMessage("Exito");
            resetFields();

        } catch (Exception e) {
            Messages.errorMessage("error");
        }
    }

    public void inactivar() {
        try {
            DaoFactory.getCiudadDAO().delete(ciudad);
            listarTabla(true);
        } catch (Exception e) {

        }
    }

    private void resetFields() {
        this.ciudad = new Ciudades();
    }

    private boolean isPostBack() {
        return FacesContext.getCurrentInstance().isPostback();
    }

    public boolean isEditando() {
        return ciudad.getId() != null;
    }

    public void listarCombo(boolean isback) throws Exception {
        try {
            if (isback == false) {
                if (isPostBack() == false) {
                    lista = DaoFactory.getCiudadDAO().getAll("ACTIVO");
                }
            } else {
                lista = DaoFactory.getCiudadDAO().getAll("ACTIVO");
            }
        } catch (Exception e) {
            throw e;
        } finally {

        }
    }
    

    public void listarTabla(boolean isback) throws Exception {
        try {
            if (isback == false) {
                if (isPostBack() == false) {
                    lista = DaoFactory.getCiudadDAO().getAll();
                }
            } else {
                lista = DaoFactory.getCiudadDAO().getAll();
            }
        } catch (Exception e) {
            throw e;
        } finally {

        }
    }

    public void listarComboById(Departamentos id) {
        try {
            if (id != null) {
                lista = DaoFactory.getCiudadDAO().getAll(id);
            } else {
                //lista = DaoFactory.getCiudadDAO().getAll("ACTIVO");
                lista = null;
            }
        } catch (Exception e) {

        }
    }

    public void test(){
        Messages.infoMessage("Update");
    }
    //constructor
    public CiudadBean() {
        this.ciudad = new Ciudades();
    }

    //Setter,getters
    public Ciudades getCiudad() {
        return ciudad;
    }

    public void setCiudad(Ciudades ciudad) {
        this.ciudad = ciudad;
    }

    public List<Ciudades> getLista() {
        return lista;
    }

    public void setLista(List<Ciudades> lista) {
        this.lista = lista;
    }

    public List<Ciudades> getListafiltro() {
        return listafiltro;
    }

    public void setListafiltro(List<Ciudades> listafiltro) {
        this.listafiltro = listafiltro;
    }
}

src/main/webapp/ciudad/ciudadform.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
    <h:head>
        <title>Ciudad</title>
        <f:metadata>
            <o:viewParam name="ciudad" value="#{ciudadbean.ciudad}"/>
        </f:metadata>
    </h:head>

    <body>
        <ui:composition template="./../templates/principal.xhtml">
            <ui:define name="content">  
                <f:event type="preRenderView" listener="#{departamentobean.listarCombo(false)}" />
                <p:growl autoUpdate="true"/>

                <h:form>
                    <p:panelGrid columns="2" class="center-panelgrid size-components">
                        <f:facet name="header">
                            <p:outputLabel value="#{ciudadbean.editando? 'EDITANDO CIUDAD' : 'INFORMACION DE CIUDAD'}"/>
                        </f:facet>

                        <p:panelGrid class="ciudad-guardar sin-borde center-panelgrid">
                            <p:graphicImage name="imagenes\city.png"/>
                        </p:panelGrid>

                        <p:panelGrid class="ciudad-guardar
                                     border-interno-none panel-contenedor">

                            <p:row>
                                <p:column>
                                    <p:outputLabel value="Descripcion ciudad" for="ciudad-descripcion"/>
                                </p:column>
                                <p:column>
                                    <p:inputText id="ciudad-descripcion" value="#{ciudadbean.ciudad.descripcion}"/>
                                </p:column>
                                <p:column>
                                    <p:message for="ciudad-descripcion"/>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <p:outputLabel value="Departamento " for="id-combo-departamento"/>
                                </p:column>
                                <p:column>
                                    <p:selectOneMenu required="true" id="id-combo-departamento" value="#{ciudadbean.ciudad.idDepartamento}" 
                                                     converter="omnifaces.SelectItemsConverter">
                                        <f:selectItem itemLabel="Seleccionar" itemValue="#{null}" noSelectionOption="true"/>
                                        <f:selectItems value="#{departamentobean.lista}" var="departamentos"
                                                       itemLabel="#{departamentos.descripcion}"
                                                       itemValue="#{departamentos}"
                                                       />
                                    </p:selectOneMenu>
                                </p:column>

                                <p:column>
                                    <p:message for="id-combo-departamento"/>
                                </p:column>
                            </p:row>

                            <p:row>
                                <p:column>
                                    <p:outputLabel value="Estado ciudad" for="ciudad-estado"/>
                                </p:column>
                                <p:column>
                                    <p:selectOneMenu required="true" id="ciudad-estado" value="#{ciudadbean.ciudad.estado}"
                                                     style="width: 150px">
                                        <f:selectItem itemLabel="Activo" itemValue="ACTIVO"/>
                                        <f:selectItem itemLabel="Inactivo" itemValue="INACTIVO"/>
                                    </p:selectOneMenu>
                                </p:column>
                                <p:column>
                                    <p:message for="ciudad-estado"/>
                                </p:column>
                            </p:row>
                            <f:facet name="footer">
                                <p:row>
                                    <p:column colspan="3">
                                        <p:commandButton value="Guardar"
                                                         style="float: right"
                                                         class="no-apply-size-components"
                                                         actionListener="#{ciudadbean.guardar}"/>
                                    </p:column>
                                </p:row>
                            </f:facet>

                        </p:panelGrid>
                    </p:panelGrid>
                </h:form>  
                <p:graphicImage width="100" height="100" cache="false"
                                value="C:\\dir\\null.png"
                                alt="Sin imagen"/>

            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/ciudad/ciudadtable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Ciudad</title>
    </h:head>

    <body>
        <ui:composition template="./../templates/principal.xhtml">
            <p:growl autoUpdate="true"/>
            <ui:define name="content">
                <f:event type="preRenderView" listener="#{ciudadbean.listarTabla(false)}"/>
                <h:form id="formCiudad">
                    <p:fieldset class="generic-fielset">

                        <p:dataTable value="#{ciudadbean.lista}" var="ciudades"
                                     id="datatable-ciudades"
                                     emptyMessage="Sin Registros"
                                     class="generic-table"
                                     rowIndexVar="linea"
                                     rows="5"
                                     paginator="true"
                                     rowsPerPageTemplate="5,10,15"
                                     paginatorPosition="bottom"
                                     widgetVar="ciudadTable"
                                     filteredValue="#{ciudadbean.listafiltro}">


                            <f:facet name="header" class="header-search">
                                <h:panelGrid columns="2">
                                        <p:inputText id="globalFilter" 
                                                 onkeyup="PF('ciudadTable').filter()" 
                                                 class="float-right"
                                                 placeholder="Escriba"/>
                                </h:panelGrid>


                            </f:facet>

                            <p:column width="120" headerText="Acciones" style="text-align: center" class="class-acciones">
                                <p:commandLink update=":form-dialog" oncomplete="PF('ciudadDialog').show()"
                                               title="View" class="acciones-hover">
                                    <f:setPropertyActionListener value="#{ciudades}" target="#{ciudadbean.ciudad}" />
                                    <p:graphicImage library="imagenes" name="view-glass.png" width="24" height="24"/>
                                </p:commandLink>
                                <p:link outcome="/ciudad/ciudadform">
                                    <f:param name="ciudad" value="#{ciudades.id}"/>
                                    <p:graphicImage library="imagenes" name="edit.png" width="24" height="24"/>
                                </p:link>

                                <p:commandLink update=":form-confirm-dialog:confirmDialog"
                                               oncomplete="PF('confirmDelete').show();">
                                    <p:graphicImage library="imagenes" name="cancel-2.png" width="24" height="24"/>
                                    <f:setPropertyActionListener value="#{ciudades}" target="#{ciudadbean.ciudad}" />

                                </p:commandLink>



                            </p:column>

                            <p:column headerText="Codigo"
                                      style="width: 120px; padding: 1px; text-align: center"
                                      filterBy="#{ciudades.id}"
                                      filterMatchMode="exact">
                                #{ciudades.id}
                            </p:column>
                            <p:column headerText="Descripción" 
                                      style="width: 400px; padding: 1px; text-align: center"
                                      filterStyleClass="filter-by-descripcion"
                                      filterBy="#{ciudades.descripcion}"
                                      filterMatchMode="contains">
                                #{ciudades.descripcion}
                            </p:column>
                            <p:column headerText="Departamento" 
                                      style="width: 400px; padding: 1px; text-align: center"
                                      filterStyleClass="filter-by-descripcion"
                                      filterBy="#{ciudades.idDepartamento.descripcion}"
                                      filterMatchMode="contains">
                                #{ciudades.idDepartamento.descripcion}
                            </p:column>
                            <p:column headerText="Estado"
                                      style="text-align: center; width: 150px"
                                      filterBy="#{ciudades.estado}"
                                      filterMatchMode="exact"
                                      >
                                <f:facet name="filter">
                                    <p:selectOneMenu onchange="PF('ciudadTable').filter()">
                                        <f:selectItem itemLabel="Seleccione" itemValue="#{null}" noSelectionOption="true" />
                                        <f:selectItem itemLabel="Activo" itemValue="ACTIVO" />
                                        <f:selectItem itemLabel="Inactivo" itemValue="INACTIVO" />
                                    </p:selectOneMenu>
                                </f:facet>
                                #{ciudades.estado}
                            </p:column>

                        </p:dataTable>
                    </p:fieldset>
                </h:form>
                <h:form id="form-dialog">
                    <p:dialog header="Ciudad Info" widgetVar="ciudadDialog" 
                              modal="true" showEffect="fade" 
                              hideEffect="fade" resizable="false">
                        <p:outputPanel id="ciudadDetail" style="text-align:center;">
                            <p:panelGrid  columns="2" rendered="#{not empty ciudadbean.ciudad}" 
                                          columnClasses="label-dialogo-view" class="panel-contenedor borde-bottom">

                                <h:outputText value="Codigo:" />
                                <h:outputText value="#{ciudadbean.ciudad.id}" />

                                <h:outputText value="Descripción" />
                                <h:outputText value="#{ciudadbean.ciudad.descripcion}" />

                                <h:outputText value="Estado:" />
                                <h:outputText value="#{ciudadbean.ciudad.estado}"/>

                                <h:panelGroup/>
                                <p:commandLink oncomplete="PF('ciudadDialog').hide()">
                                    <p:graphicImage name="imagenes\ok_image.png" style="float: right;height: 20px"
                                                    />
                                </p:commandLink>

                            </p:panelGrid>
                        </p:outputPanel>
                    </p:dialog>
                </h:form>
                <h:form id="form-confirm-dialog">
                    <p:confirmDialog id="confirmDialog"
                                     widgetVar="confirmDelete"
                                     header="Message"
                                     severity="alert"
                                     closeOnEscape="true"
                                     appendTo="@(body)"
                                     closable="true">

                        <p:commandButton id="btnYes"
                                         value="Si"
                                         process="@this"
                                         style="float: right"
                                         actionListener="#{ciudadbean.inactivar()}"
                                         oncomplete="PF('confirmDelete').hide()"
                                         update=":formCiudad:datatable-ciudades"/>

                        <p:commandButton id="btnNo"
                                         style="float: right"
                                         value="No"
                                         onclick="PF('confirmDelete').hide()"
                                         type="button" />

                        <f:facet name="message">
                            <p:outputPanel>
                                <h:outputFormat value="Se eliminara a #{ciudadbean.ciudad.descripcion}, confirmar?" escape="false"/>
                            </p:outputPanel>
                        </f:facet>
                    </p:confirmDialog>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>